name: Lib.Azure.Functions.Worker.Extensions.WebPush - CD
on:
  push:
    tags:
    - "azure-functions-worker-extensions-v[0-9]+.[0-9]+.[0-9]+"
jobs:
  deployment:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract VERSION
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/azure-functions-worker-extensions-v/}" >> $GITHUB_ENV
      shell: bash
    - name: Setup .NET Core 3.1 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x'
    - name: Setup .NET 6.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Setup .NET 8.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Setup .NET 9.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: dotnet pack --configuration Release --no-build
    - name: NuGet Push Lib.Azure.Functions.Worker.Extensions.WebPush
      run: dotnet nuget push src/Lib.Azure.Functions.Worker.Extensions.WebPush/bin/Release/Lib.Azure.Functions.Worker.Extensions.WebPush.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      shell: bash
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}