name: DocFx
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET Core 3.1 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x'
    - name: Setup .NET 6.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Setup .NET 8.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Setup .NET 9.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docfx
        path: docs/DocFx.Net.Http.WebPush/wwwroot
        retention-days: 1
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: docfx
        path: docs/DocFx.Net.Http.WebPush/wwwroot
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: docs/DocFx.Net.Http.WebPush/wwwroot